Add permissionExplanation to SERVICE_ACCOUNT property (#515)
* Add permissionExplanation to SERVICE_ACCOUNT property

* Enforce SERVICE_ACCOUNT description in schema.validate()

* Remove schema doc question marks

* Print schema validation failures as a warning in verify

* Fix lint errors

* Print schema validation warnings at end instead of inline

* Update test schemas with SERVICE_ACCOUNT description, and try downgrading to admin

* Replace cluster-admin Role to test service accounts

* Address PR comments

* Make SchemaXServiceAccount.validate() comment ref Schema.validate()

diff --git a/scripts/verify b/scripts/verify
--- a/scripts/verify
+++ b/scripts/verify
@@ -111,6 +111,14 @@ function print_summary() {
     echo "$deployer_errors" >> "$error_summary_path"
   fi
 
+  if [[ -n "$validation_errors" ]]; then
+    echo "=== SCHEMA VALIDATION WARNING ==="
+    echo "WARNING: Schema is incompatible with the latest deployer, would fail with:"
+    echo
+    echo "$validation_errors"
+    echo "=================================="
+  fi
+
   if [[ -s "$error_summary_path" ]]; then
     echo "=== ERROR SUMMARY ==="
     cat "$error_summary_path"
@@ -163,6 +171,11 @@ namespace_key="$(extract_schema_key.py \
 
 export NAME="apptest-$test_id"
 export NAMESPACE="apptest-$test_id"
+
+# Validate the schema, outputting any errors as a warning.
+set +e
+validation_errors=$(/bin/validate_schema.py --values_mode raw 2>&1)
+set -e
 
 # Stitch in name and namespace parameters.
 parameters=$(echo "$parameters" \
