Creating multiple log files for mpdev verify (#586)

diff --git a/scripts/verify b/scripts/verify
--- a/scripts/verify
+++ b/scripts/verify
@@ -59,7 +59,7 @@ done
 [[ -z "$parameters" ]] && parameters="{}"
 [[ -z "$wait_timeout" ]] && wait_timeout=600
 
-error_summary_path="$(mktemp)"
+error_summary_path="/logs/errors_summary.log"
 
 function delete_apiservices() {
   # Remove apiservices that are unavailable or attached to $NAMESPACE
@@ -80,21 +80,23 @@ function delete_apiservices() {
 function delete_namespace() {
   if [[ -z "$namespace_deleted" ]]; then
     echo "INFO Collecting events for namespace \"$NAMESPACE\""
-    kubectl get events --namespace="$NAMESPACE" || echo "ERROR Failed to get events for namespace \"$NAMESPACE\""
+    kubectl get events --namespace="$NAMESPACE" | tee "/logs/events.log" || echo "ERROR Failed to get events for namespace \"$NAMESPACE\""
+    cat "/logs/events.log"
     error_events="$(kubectl get events --namespace="$NAMESPACE" --field-selector="type!=Normal" || echo "ERROR Failed to get events for namespace \"$NAMESPACE\"")"
 
     if [[ ! -z $deployer_name ]]; then
       echo "INFO Collecting logs for deployer"
-      deployer_logs="$(kubectl logs "jobs/$deployer_name" --namespace="$NAMESPACE" --tail 9999 || echo "ERROR Failed to get logs for deployer $deployer_name")"
-      echo "$deployer_logs"
+      (kubectl logs "jobs/$deployer_name" --namespace="$NAMESPACE" --tail 9999 || echo "ERROR Failed to get logs for deployer $deployer_name") > "/logs/deployer.log"
+      cat "/logs/deployer.log" | awk '{print "DEPLOYER "$0}'
 
-      deployer_errors="$(echo "$deployer_logs" | /scripts/filter_deployer_logs.py)"
+      deployer_errors="$(cat "/logs/deployer.log" | /scripts/filter_deployer_logs.py)"
     fi
 
     delete_apiservices
     
     echo "INFO Deleting namespace \"$NAMESPACE\""
-    kubectl get all --namespace "$NAMESPACE" --output=yaml
+    kubectl get all --namespace "$NAMESPACE" --output=yaml > "/logs/resources_cleanup.yaml"
+    cat "/logs/resources_cleanup.yaml"
     kubectl delete namespace "$NAMESPACE"
     namespace_deleted="true"
   fi
@@ -300,8 +302,18 @@ while true; do
 done
 
 # Get the logs from the deployer before deleting the application. Set deployer name to empty so clean up doesn't try to get its logs again.
-kubectl logs "jobs/$deployer_name" --namespace="$NAMESPACE" || echo "ERROR Failed to get logs for deployer $deployer_name"
+(kubectl logs "jobs/$deployer_name" --namespace="$NAMESPACE" --tail 9999 || echo "ERROR Failed to get logs for deployer $deployer_name") > "/logs/deployer.log"
+cat "/logs/deployer.log" | awk '{print "DEPLOYER "$0}'
+cat "/logs/deployer.log" | grep '^SMOKE_TEST' > "/logs/tester.log" || echo "Failed to find tester logs"
+
 deployer_name=""
+
+resources_yaml="/logs/resources.yaml"
+kubectl get applications.app.k8s.io --namespace "$NAMESPACE" --output=yaml > "$resources_yaml"
+echo "---" >> "$resources_yaml"
+kubectl get all --namespace "$NAMESPACE" --output=yaml >> "$resources_yaml"
+echo "---" >> "$resources_yaml"
+kubectl get serviceaccounts,roles,rolebindings --namespace "$NAMESPACE" --output=yaml >> "$resources_yaml"
 
 echo "INFO Stop the application"
 kubectl delete "application/$NAME" \
@@ -309,6 +321,7 @@ kubectl delete "application/$NAME" \
   || clean_and_exit "ERROR Failed to stop application"
 
 deletion_timeout="$wait_timeout"
+
 echo "INFO Wait for the applications to be deleted"
 /scripts/wait_for_deletion.sh \
   --namespace="$NAMESPACE" \
