Add ONBUILD directives to deployer_helm_tiller_base.

diff --git a/marketplace/deployer_helm_tiller_base/Dockerfile b/marketplace/deployer_helm_tiller_base/Dockerfile
--- a/marketplace/deployer_helm_tiller_base/Dockerfile
+++ b/marketplace/deployer_helm_tiller_base/Dockerfile
@@ -38,3 +38,24 @@ COPY marketplace/deployer_helm_tiller_base/bin/* /bin/
 RUN mkdir -p /data/chart
 
 ENTRYPOINT ["/bin/bash", "/bin/deploy.sh"]
+
+ONBUILD COPY . /tmp/onbuild
+
+# Partner directory structure assertions.
+ONBUILD RUN if [ "$(find /tmp/onbuild -maxdepth 1 -mindepth 1 -type d -printf '\n' | wc -l)" -ne 1 ]; then \
+              >&2 echo "Too many directories." ; \
+              find /tmp/onbuild ; \
+              exit 1 ; \
+            fi ; \
+            if [ ! -f /tmp/onbuild/schema.yaml ]; then \
+              >&2 echo "Missing schema.yaml." ; \
+              find /tmp/onbuild ; \
+              exit 1 ; \
+            fi
+
+ONBUILD RUN export CHART_NAME="$(find /tmp/onbuild -maxdepth 1 -mindepth 1 -type d -printf '%P\n')" \
+            && cp /tmp/onbuild/schema.yaml /data/schema.yaml \
+            && mkdir -p /data/chart \
+            && cd /data/chart \
+            && helm package --dependency-update "/tmp/onbuild/$CHART_NAME" --destination /data/chart/ \
+            && rm -rf /tmp/onbuild
